-- MySQL Script generated by MySQL Workbench
-- Sat 16 Oct 2021 01:36:34 AM CEST
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema nettbutikk
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `nettbutikk` ;
USE `nettbutikk` ;

-- -----------------------------------------------------
-- Table `nettbutikk`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `nettbutikk`.`user` (
  `userid` INT NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(16) NOT NULL,
  `email` VARCHAR(255) NULL,
  `password` VARCHAR(32) NOT NULL,
  `create_time` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `name` VARCHAR(45) NULL,
  `adress` VARCHAR(45) NULL,
  PRIMARY KEY (`userid`));


-- -----------------------------------------------------
-- Table `nettbutikk`.`number`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `nettbutikk`.`number` (
  `number` INT NOT NULL,
  `user_userid` INT NOT NULL,
  PRIMARY KEY (`number`, `user_userid`),
  INDEX `fk_number_user_idx` (`user_userid` ASC) VISIBLE,
  CONSTRAINT `fk_number_user`
    FOREIGN KEY (`user_userid`)
    REFERENCES `nettbutikk`.`user` (`userid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `nettbutikk`.`order`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `nettbutikk`.`order` (
  `orderid` INT NOT NULL AUTO_INCREMENT,
  `user_userid` INT NOT NULL,
  PRIMARY KEY (`orderid`, `user_userid`),
  INDEX `fk_order_user1_idx` (`user_userid` ASC) VISIBLE,
  CONSTRAINT `fk_order_user1`
    FOREIGN KEY (`user_userid`)
    REFERENCES `nettbutikk`.`user` (`userid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `nettbutikk`.`product`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `nettbutikk`.`product` (
  `productid` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  `price` INT NOT NULL,
  `amount` INT(2) NOT NULL,
  `order_orderid` INT NOT NULL,
  `order_user_userid` INT NOT NULL,
  PRIMARY KEY (`productid`),
  INDEX `fk_product_order1_idx` (`order_orderid` ASC, `order_user_userid` ASC) VISIBLE,
  CONSTRAINT `fk_product_order1`
    FOREIGN KEY (`order_orderid` , `order_user_userid`)
    REFERENCES `nettbutikk`.`order` (`orderid` , `user_userid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
